**SETUP CONNECTION**

In [17]:
import psycopg2
from db_secrets import user,password
import pandas as pd 


DATABASE = "recitation_3"

print(password)

conection = psycopg2.connect(database=DATABASE,user=user,password=password, host="localhost")

cursor = conection.cursor()

def print_query(query):
    try:
        cursor.execute(query)
        labels = [col.name for col in cursor.description]
        return pd.DataFrame(cursor.fetchall(), columns=labels)
    except Exception as e:
        conection.rollback()
        print("Error:", e)

        


query = """
SELECT DISTINCT con FROM star 
    ORDER BY con DESC;
"""

print_query(query)

1111

    con
0   NaN
1   Vul
2   Vol
3   Vir
4   Vel
..  ...
84  Aqr
85  Aql
86  Aps
87  Ant
88  And

[89 rows x 1 columns]

### 8. Stars with sp ectral typ e `M' in constellation Pisces.

In [18]:
query = """ 
SELECT s.id, s.proper_name
FROM star AS s
JOIN constellation AS c ON s.con = c.abbr
WHERE c.name = 'Pisces'
  AND s.spectral_type LIKE 'M%'; -- this makes that it checks the first letter
"""

print_query(query)

         id proper_name
0         6        None
1       154        None
2       263        None
3       578        None
4       895        None
..      ...         ...
110  118087        None
111  118103        None
112  119571        None
113  119577        None
114  119605        None

[115 rows x 2 columns]

### 10. The 100 stars closest to the sun.

In [19]:
query = """ 
SELECT n.id,
       n.proper_name,
       ABS(n.x_pc - s.x_pc) AS x_diff,
       ABS(n.y_pc - s.y_pc) AS y_diff,
       ABS(n.z_pc - s.z_pc) AS z_diff,
       (ABS(n.x_pc - s.x_pc) * ABS(n.x_pc - s.x_pc) + 
        ABS(n.y_pc - s.y_pc) * ABS(n.y_pc - s.y_pc) +
        ABS(n.z_pc - s.z_pc) * ABS(n.z_pc - s.z_pc)) AS distance_pow_2
    FROM star as n CROSS JOIN star as s 
    WHERE 
        s.proper_name ILIKE 'Sol' AND 
        n.id <> s.id
    ORDER BY distance_pow_2 ASC LIMIT 100; 

"""

print_query(query)

        id       proper_name    x_diff    y_diff    z_diff  distance_pow_2
0    70666  Proxima Centauri  0.472269  0.361451  1.151219        1.678990
1    71453           Toliman  0.495186  0.413973  1.156674        1.754478
2    71456   Rigil Kentaurus  0.495208  0.414084  1.156625        1.754478
3    87665    Barnard's Star  0.017378  1.816613  0.149123        3.322622
4   118720          Wolf 359  2.282816  0.649334  0.292057        5.718181
..     ...               ...       ...       ...       ...             ...
95   75841               NaN  2.678399  3.561312  3.911408       35.155877
96   84147          Guniibuu  1.027051  5.204798  2.656955       35.204166
97    3814            Achird  3.098457  0.674227  5.038376       35.440251
98  118021               NaN  3.098391  0.673787  5.038550       35.441002
99   37659               NaN  2.621894  5.336048  0.369099       35.483970

[100 rows x 6 columns]

###  11. The 100 stars closest to the star with proper name Antares (do not plug in the coordinates of this star
in SQL. The literal `Antares' must be in your SQL)

In [20]:
query = """ 
SELECT n.id,
       n.proper_name,
       ABS(n.x_pc - s.x_pc) AS x_diff,
       ABS(n.y_pc - s.y_pc) AS y_diff,
       ABS(n.z_pc - s.z_pc) AS z_diff,
       (ABS(n.x_pc - s.x_pc) * ABS(n.x_pc - s.x_pc) + 
        ABS(n.y_pc - s.y_pc) * ABS(n.y_pc - s.y_pc) +
        ABS(n.z_pc - s.z_pc) * ABS(n.z_pc - s.z_pc)) AS distance_pow_2
    FROM star as n CROSS JOIN star as s 
    WHERE 
        s.proper_name ILIKE 'Antares' AND 
        n.id <> s.id
    ORDER BY distance_pow_2 ASC LIMIT 100; 

"""

print_query(query)

       id proper_name     x_diff     y_diff     z_diff  distance_pow_2
0   80938         NaN   3.078432   2.190751   3.432893       26.060888
1   80944         NaN   4.739820   1.898407   1.749059       29.129050
2   80574         NaN   0.199982   0.999385   5.425223       30.471808
3   79807         NaN   3.978069   5.680998   5.995074       84.039684
4   81279         NaN   7.774334   2.475877   5.523168       97.075621
..    ...         ...        ...        ...        ...             ...
95  81898         NaN   4.941132  22.128246  12.965781      682.185533
96  83402         NaN  22.515609   9.595595   9.436476      688.075171
97  78810         NaN   3.181474  24.066836  10.451689      698.572175
98  78113         NaN  11.106021  19.838511  13.626258      702.585128
99  78838         NaN   1.838698  26.094650   4.901775      708.338967

[100 rows x 6 columns]